language: python

python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - python manage.py test -y

services:
  - postgresql

before_script:
  - psql -c "CREATE USER root WITH password 'root';ALTER USER root CREATEDB;" -U postgres
