language: python

python:
  - 3.6
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install
  - psql -c "CREATE USER root WITH password 'root';ALTER USER root CREATEDB;" -U postgres
script:
  - python manage.py test --no-input
