# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_id',
            field=models.IntegerField(default=0),
        ),
    ]
