# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='receiver_id',
            new_name='reciever_id',
        ),
    ]
