# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180102_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_room_id',
            new_name='chat_room',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='chat_room_id',
        ),
        migrations.AddField(
            model_name='friends',
            name='chat_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.ChatRoom'),
        ),
    ]
