# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('user_profile', '0003_auto_20171115_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('birth_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='reciever_id',
            new_name='receiver_id',
        ),
    ]
