# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0004_auto_20180104_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToPairChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='status',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='usertopairchatroom',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.ChatRoom'),
        ),
        migrations.AddField(
            model_name='usertopairchatroom',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertopairchatroom_pair_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertopairchatroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertopairchatroom_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
