# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20171121_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
