# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20180128_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='read', max_length=20),
            preserve_default=False,
        ),
    ]
