# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20171213_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
