# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20171213_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='friend_id',
            new_name='friend',
        ),
    ]
