# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0012_auto_20171213_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_id',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=models.SET(user_profile.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
