# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0013_auto_20171213_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=models.SET(user_profile.models.get_deleted_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
